### ISSUE TITLE
请问这个工具类目前支持 milvus 的 DynamicField 模式吗

### ISSUE THREAD

**Issue by 1402564807** [JDK-Plus/spring-boot-starter-milvus#1]
请问这个工具类目前支持 milvus 的 DynamicField 模式吗

**Comment by p-moon** [comment]
目前还不支持，我这边暂时没这个需求，欢迎贡献代码哈

**Comment by p-moon** [comment]
你好！首先，非常感谢你提出这个需求并对我的项目感兴趣。我要坦诚地告诉你，目前我正陷入繁忙的工作中，难以抽出时间来满足这个需求。然而，我非常欣赏你的热情和贡献意愿。

我想提出一个建议，如果你愿意的话，可以尝试自行修改这个功能，然后进行测试确保它正常运作。一旦你确认一切都运行良好，我鼓励你发起一个合并请求（Merge Request），将你的修改提交给我。这将有助于我们一起改进并丰富这个软件项目，为更多人创造更好的体验。

再次感谢你的支持和理解，期待看到你的贡献。一起努力，让这个项目变得更加出色！
